### ISSUE TITLE
Doesn't work on Elixir 1.0.x

### ISSUE THREAD

**Issue by alg** [yrashk/relex#18]
Here's what I get when compiling the app.

```
= Compilation error on file lib/app.ex ==
** (CompileError) lib/app.ex:1: undefined function defrecord/3
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_exp.erl:49: :elixir_exp.expand/2
    (elixir) src/elixir.erl:206: :elixir.quoted_to_erl/3
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

There isn't such thing as `defrecord` any more if I'm not mistaken. It's been replaced with Structure?
